# .pre-commit-config.yaml
repos:
  - repo: https://github.com/psf/black
    rev: 23.3.0  # Specify the desired version
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/Sir-Morara/pre-commit-hooks
    rev: v1.0.0  # Use the tag you created in your custom hooks repo
    hooks:
      - id: flake8


      - id: isort
      

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991  # Specify the desired version
    hooks:
      - id: mypy
        name: Mypy
        types: [python]
        additional_dependencies: [types-requests]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0  # Specify the desired version
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
