name: 'Lint Code'

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  lint_python:
    name: Lint Python Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black isort autoflake flake8

      - name: Run Black (Code Formatter)
        run: |
          black djangoapp/ djangoproj/ frontend/
      
      - name: Run isort (Sort Imports)
        run: |
          isort djangoapp/ djangoproj/ frontend/
      
      - name: Run autoflake (Remove Unused Imports)
        run: |
          autoflake --remove-all-unused-imports --recursive --in-place djangoapp/ djangoproj/ frontend/
      
      - name: Remove Trailing Whitespace
        run: |
          find djangoapp/ djangoproj/ frontend/ -type f -name "*.py" -exec sed -i 's/[ \t]*$//' {} +
      
      - name: Run Flake8 (Lint Python Files)
        run: |
          flake8 djangoapp/ djangoproj/ frontend/
      
      - name: Lint Python Complete
        run: echo "Linted all the Python files successfully"

  lint_js:
    name: Lint JavaScript Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install JSHint
        run: npm install jshint --global

      - name: Run JSHint (Lint JavaScript Files)
        run: |
          # This command finds all JavaScript files recursively and runs JSHint on them
          find ./server/database -name "*.js" -exec jshint {} +
          echo "Linted all the JS files successfully"
